showNotBar: false
barBody: "**Prices are increasing January 1st.** Lock in current pricing by
  becoming a paid customer before 2022."
arrowText: Learn more
url: /blog/price-change-2021/
openUrlNewTab: false
backgroundColor: "#20265a"
